### ISSUE TITLE
some images are not loading

### ISSUE THREAD

**Issue by aqibgatoo** [eclipsesource/tabris-js-docs#3]
![tabrisjs](https://user-images.githubusercontent.com/4655062/37865978-010da72c-2faa-11e8-9a4a-b4b46b9c7657.png)

**Comment by mpost** [comment]
Thanks for pointing the broken links out. We will investigate the issue.

**Comment by aqibgatoo** [comment]
i would like to add that i have pointed only a few ones it is almost a usual affair across the documentation.

**Comment by mpost** [comment]
Yes, there is a problem when resolved relative URLs on our servers. Please stay tuned.

**Comment by aqibgatoo** [comment]
The problem has been resolved. The URLs are now loading correctly.
